### ISSUE TITLE
Problema al enviar datos 

### ISSUE THREAD

**Issue by xLinconx** [gozozo/openpay-server#3]
tengo este error al crear el usuario: 

> {"response":"error","class":"OpenpayApiRequestError","error":{"code":0,"message":"Invalid parameters type detected (type 'NULL' received, Array expected)","http_code":0,"category":""}}

esto es lo que se envía en los headers:

> external_id:2
name:customer name
last_name:
email:customer_email@me.com
requires_account:false
phone_number:44209087654
address[line1]:Calle 10
address[line2]:col. san pablo
address[line3]:entre la calle 1 y la 2
address[state]:Queretaro
address[city]:Queretaro
address[postal_code]:76000
address[country_code]:MX

y esta es la url a la que se lo envío:
> http://localhost:8000/openpay/customer

en el archivo .env tengo los siguientes datos:

> OPENPAY_ID =_mi_id_proporcionado
> OPENPAY_SK=sk_llave_proporcionada_por_ellos
> OPENPAY_TABLE = users
> OPENPAY_REFERENCE = id

**Comment by gozozo** [comment]
Hola

Puedes tratar con postman es una exención gratis de Google Chrome y se debería de mandar la petición de la siguiente manera y así probar el servicio

parameters:{"external_id" : "1","name" : "customer name","last_name" : "","email" : "customer_email@me.com","requires_account" : false,"phone_number" : "44209087654","address" : {"line1" : "Calle 10","line2" : "col. san pablo","line3" : "entre la calle 1 y la 2","state" : "Queretaro","city" : "Queretaro","postal_code" : "76000","country_code" : "MX"}}




O en un formulario en un input puedes ponerlo así y es una POST, pero esto esta pensado mas para funcionar como web service por lo que te recomiendo no usarlos así por la respuesta que regresa en un JSON pero lo puedes poner un AJAX

<input type="hidden" name="parameters" value="{"external_id" : "","name" : "customer name","last_name" : "","email" : "customer_email@me.com","requires_account" : false,"phone_number" : "44209087654","address" : {"line1" : "Calle 10","line2" : "col. san pablo","line3" : "entre la calle 1 y la 2","state" : "Queretaro","city" : "Queretaro","postal_code" : "76000","country_code" : "MX"}}” >


Espero que te ayude.

Saludos!
